declare -A language_map
language_map["Portugues"]="Portuguese"
language_map["Romansh"]="Romanian"
language_map["Francais"]="French"
language_map["Français"]="French"
language_map["Ukranian"]="Ukrainian"
language_map["Español"]="Spanish"
language_map["Slovenščina"]="Slovene"
language_map["Vietnamese/tiếng Việt"]="Vietnamese"
language_map["English American"]="English"
