declare -A m3ufields_map
m3ufields_map["EXTGENRE"]="Genre"
m3ufields_map["PLAYLIST"]="Name"
m3ufields_map["EXTIMG"]="Image"
m3ufields_map["HOMEPAGE"]="Homepage"
m3ufields_map["COUNTRY"]="Country"
m3ufields_map["STATE"]="State"
m3ufields_map["CODEC"]="Codec"
m3ufields_map["BITRATE"]="Bitrate"
m3ufields_map["LANGUAGE"]="Language"
m3ufields_map["DESCRIPTION"]="Description"
