declare -A m3ufields_map
m3ufields_map["EXTGENRE"]="Genre"
m3ufields_map["PLAYLIST"]="Name"
m3ufields_map["EXTIMG"]="Image"
m3ufields_map["HOMEPAGE"]="Homepage"
m3ufields_map["COUNTRY"]="Country"
m3ufields_map["STATE"]="State"
m3ufields_map["REGION"]="Region"
m3ufields_map["CODEC"]="Codec"
m3ufields_map["BITRATE"]="Bitrate"
m3ufields_map["LANGUAGE"]="Languages"
m3ufields_map["DESCRIPTION"]="Description"
m3ufields_map["ADDED"]="Added"
m3ufields_map["LASTMODIFIED"]="Last-Modified"
