# This workflow test the webradio add/modify/delete actions

name: test
on:
  push:
    paths:
    - 'build.sh'
    - 'test/*'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: installdeps
      run: sudo apt install imagemagick

    - name: test
      run: ./test/test.sh
